@url = http://localhost:5555

### GET home
GET {{ url }}

### GET info
GET {{ url }}/info

### GET config
GET {{ url }}/config

### POST config
POST {{ url }}/config
Content-Type: application/json

{
  "title": "test",
  "refreshInterval": 600,
  "shortcuts": [
    {
      "key": "j",
      "title": "Next",
      "command": "next"
    }
  ]
}

### GET feeds
GET {{ url }}/feeds

### POST feed
POST {{ url }}/feeds
Content-Type: application/json

{
  "categories": [
    "programming",
    "random"
  ],
  "htmlUrl": "https://akrabat.com",
  "id": "http://akrabat.com/feed/",
  "lastUpdated": "2024-07-02T21:24:53.000Z",
  "text": "Rob Allen!",
  "title": "Rob Allen",
  "type": "rss",
  "xmlUrl": "https://akrabat.com/feed/"
}

### GET feed-details
GET {{ url }}/feed-details?url=http://akrabat.com/feed/
